export { default as hero } from './Hero'
export { default as twoColumn } from './twoColumn'
export { default as textWithIllustration } from './textWithIllustration'
export { default as textWithVideo } from './textWithVideo'
export { default as illustration } from './illustration'
export { default as videoPlug } from './videoPlug'
export { default as video } from './video'
// export { default as ctaColumns } from './ctaColumns'
// export { default as ctaPlug } from './ctaPlug'
// export { default as uiComponentRef } from './uiComponent'
// export { default as pricing } from './pricing'
